from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .errors import DomainError


class TerminologyPort(Protocol):
    def lookup(self, system: str, code: str, version: str) -> dict: ...
    def expand(self, value_set_ref: dict) -> list[dict]: ...
    def translate(self, concept: dict, target_system: str) -> list[dict]: ...
    def validate_code(self, concept: dict) -> dict: ...


class InferencePort(Protocol):
    def validate_model(self, model_ref: dict) -> dict: ...
    def evaluate(self, request: dict) -> dict: ...
    def explain(self, evaluation_ref: str) -> dict: ...


class FacilityPort(Protocol):
    def list_capabilities(self) -> list[dict]: ...
    def availability(self, capability_ref: str) -> dict: ...
    def hold(self, request: dict) -> dict: ...
    def confirm(self, receipt: dict) -> dict: ...
    def cancel(self, receipt: dict) -> dict: ...
    def reconcile(self, command_ref: str) -> dict: ...


@dataclass
class UnavailableAdapter:
    capability: str

    def __getattr__(self, _name):
        def unavailable(*_args, **_kwargs):
            raise DomainError("capability_unavailable", 503, f"Adaptateur {self.capability} non configuré.", retryable=False)
        return unavailable
